# Generated by Django 3.1.7 on 2021-03-23 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostAutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAutor', models.CharField(default='', max_length=255)),
                ('saga', models.CharField(default='', max_length=255)),
                ('imagenAutor', models.ImageField(upload_to='static/img/autores')),
            ],
        ),
        migrations.CreateModel(
            name='PostLibro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLibro', models.CharField(default='', max_length=255)),
                ('imagenLibro', models.ImageField(upload_to='static/img/libros')),
                ('saga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.postautor')),
            ],
        ),
    ]
