# Generated by Django 3.1.7 on 2021-03-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_postautor_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postautor',
            name='descripcion',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
